# -*- coding: utf-8 -*-
"""Areli.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1kkLnSZYhGcK85Cqjxln11zsyhogyF0NS
"""

#@markdown Metodo para validar valores introducidos

def validacion(datoIn):
  if(datoIn < 0 and datoIn > 199):
    print('Ingrese un valor valido en el rango del 0 al 199')
    return False
  return True

#@markdown #Quicksort

def quickSort(array):
  menor = []
  igual = []
  mayor = []
  if len(array) > 1:
    pivote = array[0]
    for i in array:
      if i < pivote:
        menor.append(i)
      elif i == pivote:
        igual.append(i)
      else:
        mayor.append(i)
    return quickSort(menor)+igual+quickSort(mayor)
  else:
    return array

#@markdown Encontrar punto medio del arreglo

def puntoMedio(array, inicial):
  izq = None
  der = None
  for i in range(len(array)):
    if inicial < array[i]:
      if (i - 1 == -1):
        izq = None
        der = array[i]
        #print('Se uso 1')
        break
      else:
        izq = array[i - 1]
        der = array[i]
        #print('Se uso 1 alt')
        break
  if (izq == None and der == None):
    izq = array[-1]
    der = None
    #print('Es digito es mayor a que existe en el arreglo')
  #print('El punto de atras es,', izq, 'el de adelante es', der)
  return izq, der


"""
A = [14, 37, 65, 67, 98, 122, 124, 183]
inicial = 66
puntoMedio(A, inicial)

while(True):
  dato = int(input('Ingresar un valor del 0 al 199: '))
  if(validacion(dato)):
    break
"""